---
title: "googleVis 테스트"
author: "eunkwang"
date: "2017년 8월 21일"
output: html_document
---

## 라이브러리 로드

```{r libraryload, message=FALSE, echo=FALSE}
library(googleVis)
library(dplyr)

# 차트 생성을 위한 옵션 처리
op <- options(gvis.plot.tag='chart')

```

## 데이터로드

샘플 데이터는 다음과 같은 구조를 가짐   

1. newName : 그룹 정보, name1과 name10 이 존재
2. weekStartDate : 집계 주간의 월요일 날짜
3. period : 집계 주간
4. value1 : 집계 지표 1
5. value2 : 집계 지표 2
6. value2PerValue1 : 집계 지표 1 당 평균 집계 지표 2

```{r dataload}

df <- read.csv("raw.csv", header = TRUE, encoding = 'UTF-8', stringsAsFactors = FALSE)

head(df)

```

## 데이터 처리

날짜 데이터는 데이터 타입이 Date 여야 함

```{r manipulation}
df$weekStartDate <- as.Date(df$weekStartDate)

```



## 그래프 생성

그래프는 다음과 같이 지정하여 생성해야 함

1. idvar = 그룹 컬럼
2. timevar = 기간 컬럼, 해당 컬럼은 date 타입이어야 함
3. xvar = x축 값, 해당 컬럼은 numeric 타입이어야 함
4. yvar = y축 값, 해당 컬럼은 numeric 타입이어야 함
5. sizevar = 버블크기, 해당 컬럼은 numeric 타입이어야 함

```{r appannie, echo=FALSE, results='asis'}
myStateSettings <- '
{"colorOption":"_UNIQUE_COLOR","sizeOption":"_UNISIZE"}
'

M <- gvisMotionChart(df,
                     idvar="newName", 
                     timevar="weekStartDate",
                     xvar="value1", 
                     yvar="value2",
                     sizevar = "value2PerValue1",
                     options=list(width=1000, height=800, state=myStateSettings)
                     )

plot(M) # 생성된 그래프 객체를 html 로 변환하여 표기
```

```{r resetOptions, message=FALSE, echo=FALSE}
options(op)  # 초기에 저장한 옵션으로 복귀
```
